### ISSUE TITLE
Cannot Read Property Length of Null

### ISSUE THREAD

**Issue by J4Wx** [winseros/gulp-armapbo-plugin#1]
My gulpfile is as follows:
```
const gulp = require ('gulp');
const pbo = require ('gulp-armapbo');

gulp.task('pack', () => {
    return gulp.src('src/**')
        .pipe(pbo({
			progress: true,
			verbose: true
		}))
        .pipe(gulp.dest('./pbo-packed'));
});
```

I constantly get the same error, which is

```\node_modules\gulp-armapbo\dist\core\pboBuilder.js:19
            const entry = new headerEntry_1.HeaderEntry(file.relative, packingMethod, fileData.length, timeStamp);
                                                                                              ^

TypeError: Cannot read property 'length' of null
    at files.map.file (E:\GitLab\XenonLife-Updateomat\node_modules\gulp-armapbo\dist\core\pboBuilder.js:19:95)
    at Array.map (native)
    at PboBuilder.build (E:\GitLab\XenonLife-Updateomat\node_modules\gulp-armapbo\dist\core\pboBuilder.js:15:31)
    at PboTransformStream._flush (E:\GitLab\XenonLife-Updateomat\node_modules\gulp-armapbo\dist\core\pboTransformStream.js:23:36)
    at PboTransformStream.<anonymous> (_stream_transform.js:118:12)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:86:13)
    at PboTransformStream.emit (events.js:186:7)
    at prefinish (_stream_writable.js:500:12)
    at finishMaybe (_stream_writable.js:508:7)
```

**Comment by winseros** [comment]
Hi, there!

Thank you for your report.

I found what was causing the issue and will make a fix soon.

As a quick workaround you may use a bit another glob pattern: `'src/**/*'` instead of `'src/**'`. So your resulting code would look like this:

```
const gulp = require ('gulp');
const pbo = require ('gulp-armapbo');

gulp.task('pack', () => {
    return gulp.src('src/**/*')
        .pipe(pbo({
			progress: true,
			verbose: true
		}))
        .pipe(gulp.dest('./pbo-packed'));
});
```

**Comment by J4Wx** [comment]
I tried this too, and still suffer the same error...

Thanks

**Comment by winseros** [comment]
I made a hotfix, could you check the 1.1.1 version?

**Comment by J4Wx** [comment]
That works as expected now, thanks!

**Comment by winseros** [comment]
Ok, closing then
